### ISSUE TITLE
Did you ever start writing using different tools?

### ISSUE THREAD

**Issue by aaron-junot** [marekaf/gcr-lifecycle-policy#2]
The readme and the [medium article](https://medium.com/faun/google-container-registry-lifecycle-policy-for-images-retention-e0bc6bb88246) that led me here mention that you want to rewrite using py-kubeng and docker-py. Just was wondering if that was still something you were planning on doing because I might be interested while we're waiting on Google to implement a lifecycle feature natively.

**Comment by marekaf** [comment]
Hi @aaron-suarez! Thanks for reaching out. I forgot about it:) I'd try to write it in golang if I find some time in the upcoming two weeks. Would that suit you?

**Comment by aaron-junot** [comment]
Yeah, that would be cool. I know Python much better than I know Go if you were looking for help with it. I'm just thinking something more reliable than bash/jq would be ideal 😅  Since it's your project, totally up to you

**Comment by marekaf** [comment]
I started in Go already. I implemented some basic listing, filtering, configuration parameters. I'm going continue with the k8s integration and implementing a proper cleanup in the following days hopefully:) 
you can watch the progress if that's your thing 😅  https://github.com/marekaf/gcr-lifecycle-policy/pull/3/files

**Comment by AgrimPrasad** [comment]
This would be very helpful. Looking forward to the rewrite in Go, can help if needed. 

Also, could we also check other places where images might be used, e.g. Google Cloud Run?

**Comment by marekaf** [comment]
> This would be very helpful. Looking forward to the rewrite in Go, can help if needed.
> 
> Also, could we also check other places where images might be used, e.g. Google Cloud Run?

I will try to finish the rewrite with only few features but I'll make it fairly modular so it is easy to add a feature for scanning Google Cloud Run:) 

FYI: I'm super busy this week, I will try to make some progress on the weekend. I push all my progress to that branch.

**Comment by marekaf** [comment]
Again I was too busy :( It partially works without the actual cleaning but that is just the detail. I really hope to finish it in the upcoming weeks:)

**Comment by marekaf** [comment]
done, sorry that it took so long! 
Take it as an early alpha and feel free to test it yourself:) I expect it to be buggy but rather than letting everybody to wait even longer I released it so it gives me some quick feedback.

**Comment by marekaf** [comment]
can close this now:)
