### ISSUE TITLE
License

### ISSUE THREAD

**Issue by josephfinlayson** [marekaf/gcr-lifecycle-policy#4]
This is a great project and I want to fork it. 

Could you add a license for it? Preferably MIT

**Comment by marekaf** [comment]
Thanks!
I'm rewriting this to Golang and have MIT already there:) https://github.com/marekaf/gcr-lifecycle-policy/blob/mb-rewrite-2-go/LICENSE

**Comment by marekaf** [comment]
added to master too! https://github.com/marekaf/gcr-lifecycle-policy/blob/master/LICENSE

**Comment by josephfinlayson** [comment]
Thank you!
