### ISSUE TITLE
Artifact Registry support

### ISSUE THREAD

**Issue by yteraoka** [marekaf/gcr-lifecycle-policy#6]
Hi, 

Google is going to migrate from GCR to Artifact Registry.
I want to use `gcr-lifecycle-policy` with Artifact Registry too.
Then, I tried that. Unfortunately, Artifact Registry Docker API always returns `timeCreatedMs` with zero.

So, I propose that change the sort key in `internal/worker/sort.go` to `timeUploadedMs`. Is this acceptable?

Response from Artifact Registry

```json
{
  "child": [],
  "manifest": {
    "sha256:0efad4d09a419dc6d574c3c3baacb804a530acd61d5eba72cb1f14e1f5ac0c8f": {
      "imageSizeBytes": "0",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "tag": [
        "1.19.0"
      ],
      "timeCreatedMs": "0",
      "timeUploadedMs": "1605063108339"
    },
    "sha256:4949aa7259aa6f827450207db5ad94cabaa9248277c6d736d5e1975d200c7e43": {
      "imageSizeBytes": "0",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "tag": [
        "1.19.3"
      ],
      "timeCreatedMs": "0",
      "timeUploadedMs": "1605078050615"
    },
    "sha256:794275d96b4ab96eeb954728a7bf11156570e8372ecd5ed0cbc7280313a27d19": {
      "imageSizeBytes": "0",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "tag": [
        "1.19.2"
      ],
      "timeCreatedMs": "0",
      "timeUploadedMs": "1605078036805"
    },
    "sha256:a5a1e8e5148de5ebc9697b64e4edb2296b5aac1f05def82efdc00ccb7b457171": {
      "imageSizeBytes": "0",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "tag": [
        "1.19.1"
      ],
      "timeCreatedMs": "0",
      "timeUploadedMs": "1605078022097"
    }
  },
  "name": "myproject/example/nginx",
  "tags": [
    "1.19.0",
    "1.19.1",
    "1.19.2",
    "1.19.3"
  ]
}
```

**Comment by marekaf** [comment]
Hi @yteraoka! Thanks for submitting this issue, I will look into it (hopefully until the end of the week). The json response is super helpful too!

**Comment by marekaf** [comment]
I looked a it for a bit and it really seem that `timeCreatedMs` is always 0.
I implemented a new sorting by `timeUploadedMs` and made it configurable by cli parameter `--sort-by="timeUploadedMs"`, having the `timeCreatedMs` as a default value. 

Another problem with Artifact Registry is that it returns also `imageSizeBytes` as 0 everywhere :(

**Comment by marekaf** [comment]
@yteraoka mind taking a look?:) https://github.com/marekaf/gcr-lifecycle-policy/pull/7

**Comment by yteraoka** [comment]
@marekaf 
Thank you for your prompt response. 👍

**Comment by yteraoka** [comment]
https://github.com/marekaf/gcr-lifecycle-policy/pull/7#discussion_r521742962

**Comment by marekaf** [comment]
> [#7 (comment)](https://github.com/marekaf/gcr-lifecycle-policy/pull/7#discussion_r521742962)

how about now?

**Comment by yteraoka** [comment]
Thanks, It worked fine.
