### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by yteraoka** [marekaf/gcr-lifecycle-policy#9]
Date format in `internal/worker/print.go` is `2006-02-01`. This means `YYYY-DD-MM`.
Is this what you intended?
I prefer ISO 8601 standard `YYYY-MM-DD` (`2006-01-02`)

https://github.com/marekaf/gcr-lifecycle-policy/blob/38b0fa6598c60e8808bbd4c084e75bb88688e6d9/internal/worker/print.go#L59-L60

https://github.com/marekaf/gcr-lifecycle-policy/blob/38b0fa6598c60e8808bbd4c084e75bb88688e6d9/internal/worker/print.go#L111-L112

**Comment by marekaf** [comment]
Hi, the `YYYY-DD-MM` format is indeed what i intended. It's quite common to put `day` before `month` in my country and [some countries in EU](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Europe#:~:text=Official%20EU%20documents%20still%20tend,YYYY%2DMM%2DDD.%22) (as opposite to US where something like `YYYY-MM-DD` is much more common).

But I'm totally fine with switching to ISO 8601. I'll create a PR later.

**Comment by marekaf** [comment]
#12

**Comment by yteraoka** [comment]
Thanks

**Comment by marekaf** [comment]
merged, we can close this issue now:) thanks again
